// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 402
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(402, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsReviewExisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_EXISTED.String() && e.Code == 403
}

func ErrorReviewExisted(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_REVIEW_EXISTED.String(), fmt.Sprintf(format, args...))
}

func IsReplyExisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REPLY_EXISTED.String() && e.Code == 404
}

func ErrorReplyExisted(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_REPLY_EXISTED.String(), fmt.Sprintf(format, args...))
}

func IsStoreNotMatch(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_STORE_NOT_MATCH.String() && e.Code == 405
}

func ErrorStoreNotMatch(format string, args ...interface{}) *errors.Error {
	return errors.New(405, ErrorReason_STORE_NOT_MATCH.String(), fmt.Sprintf(format, args...))
}
